### ISSUE TITLE
x86_64 and armeabi-v7a prebuilt support

### ISSUE THREAD

**Issue by themarpe** [Lzhiyong/android-sdk-tools#23]
Hi @Lzhiyong 

Thanks for this project - trying to compile for armv7 locally at the moment, but have stumbled upon issues with Ninja getting into a CMake configuration loop (the cache remains dirty, even after 100 tries).

Would you mind adding x86_64 & armeabi-v7a prebuilts as well to the latest release?

**Comment by Lzhiyong** [comment]
I have uploaded.

**Comment by themarpe** [comment]
Hi @Lzhiyong 

With arm & x86_64 (didn't test aarch64) `fastboot` binaries, I see the following output: 

```
./fastboot devices
> 884861c3	�����N�
./fastboot devices
> 884861c3	�����
./fastboot devices
> 884861c3	����x�y�
```

And cannot decode as utf-8 as is. 

Did you also perhaps observe this? (the text in question should be `fastboot` here)

**Comment by Lzhiyong** [comment]
I have recompiled and uploaded but no tested.
