### ISSUE TITLE
How to generate these files

### ISSUE THREAD

**Issue by RohitVerma882** [Lzhiyong/android-sdk-tools#24]
How to generate .sysprop && deployagent.inc files from src?

**Comment by Lzhiyong** [comment]
> How to generate .sysprop && deployagent.inc files from src?

Building the `AOSP`

**Comment by RohitVerma882** [comment]
How to generate *.patch files from submodule

**Comment by Lzhiyong** [comment]
> How to generate *.patch files from submodule

These files are derived from manual patching, not generated by scripts, mainly because the source code may change greatly.

using diff command to generate these files
`diff -urN original_file modified_file > xxx.patch`
