### ISSUE TITLE
无法正常打包

### ISSUE THREAD

**Issue by iyutong** [lzhiyong/android-sdk-tools#26]
![Screenshot_2022-12-26-08-27-41-718_com termux](https://user-images.githubusercontent.com/84581911/209485940-2285d911-c840-41c8-ad53-e1be31e012d4.jpg)

**Comment by Lzhiyong** [comment]
找不到clang编译器，路径有错误，正确的应该是 `/data/user/0/com.termux/files/home/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang`，少了 `linux-x86_64`，用ls命令查看路径下的clang是否存在！

**Comment by iyutong** [comment]
文件存在


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 晚上6:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26)




 
找不到clang编译器，路径有错误，正确的应该是 /data/user/0/com.termux/files/home/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang，少了 linux-x86_64，用ls命令查看路径下的clang是否存在！
 
&mdash;

**Comment by Lzhiyong** [comment]
你再仔细看错误，prebuilt后面两个//，少了linux-x86_64，正确的应该是prebuilt/linux-x86_64

**Comment by Lzhiyong** [comment]
你再仔细看错误，prebuilt后面两个//，少了linux-x86_64，正确的应该是prebuilt/linux-x86_64

**Comment by iyutong** [comment]
那怎么修复？我直接运行的你的脚步


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 晚上6:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26)




 
你再仔细看错误，prebuilt后面两个//，少了linux-x86_64，正确的应该是prebuilt/linux-x86_64
 
&mdash;

**Comment by Lzhiyong** [comment]
请注意 不要使用proot容器，确保你的手机是aarch64架构，直接在termux里进行编译

**Comment by iyutong** [comment]
就是直接在termux里面打包的，是arm64架构CPU


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 晚上7:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26)




 
请注意 不要使用proot容器，确保你的手机是aarch64架构，直接在termux里进行编译
 
&mdash;

**Comment by Lzhiyong** [comment]
使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake

```python
# 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake

command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja"
```

**Comment by iyutong** [comment]
我有一个问题，就是你编译的这些文件是否可以在任意andriod终端模拟器中运行。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 晚上7:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26)




 
使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake
 # 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja"
 
&mdash;

**Comment by Lzhiyong** [comment]
> 我有一个问题，就是你编译的这些文件是否可以在任意andriod终端模拟器中运行。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月27日(周二) 晚上7:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake # 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja" &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可执行文件都是ndk编译的，与使用哪个终端无关，与编译时使用的plaform有关，我都是使用api 28进行编译的，也就是说android 9以下可能缺失某些函数，文件或许不能正常执行，找不到某些符号

**Comment by iyutong** [comment]
为什么不兼容到andriod7？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 晚上7:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26)




  
我有一个问题，就是你编译的这些文件是否可以在任意andriod终端模拟器中运行。
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月27日(周二) 晚上7:18 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake # 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
可执行文件都是ndk编译的，与使用哪个终端无关，与编译时使用的plaform有关，我都是使用api 28进行编译的，也就是说android 9以下可能缺失某些函数，文件或许不能正常执行，找不到某些符号
 
&mdash;

**Comment by Lzhiyong** [comment]
> 为什么不兼容到andriod7？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月27日(周二) 晚上7:32 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 我有一个问题，就是你编译的这些文件是否可以在任意andriod终端模拟器中运行。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月27日(周二) 晚上7:18 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake # 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 可执行文件都是ndk编译的，与使用哪个终端无关，与编译时使用的plaform有关，我都是使用api 28进行编译的，也就是说android 9以下可能缺失某些函数，文件或许不能正常执行，找不到某些符号 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

其实还是为了减少打补丁，这也就是为什么android-sdk-tools要使用 api 30来进行编译，你看termux官方的android-tools的补丁是非常多的，每次更新都要重新打补丁，还是挺麻烦的

**Comment by iyutong** [comment]
如何判断可执行文件最低兼容andriod几？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月27日(周二) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26)




  
为什么不兼容到andriod7？
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月27日(周二) 晚上7:32 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 我有一个问题，就是你编译的这些文件是否可以在任意andriod终端模拟器中运行。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月27日(周二) 晚上7:18 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake # 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 可执行文件都是ndk编译的，与使用哪个终端无关，与编译时使用的plaform有关，我都是使用api 28进行编译的，也就是说android 9以下可能缺失某些函数，文件或许不能正常执行，找不到某些符号 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
其实还是为了减少打补丁，这也就是为什么android-sdk-tools要使用 api 30来进行编译，你看termux官方的android-tools的补丁是非常多的，每次更新都要重新打补丁，还是挺麻烦的
 
&mdash;

**Comment by Lzhiyong** [comment]
> 如何判断可执行文件最低兼容andriod几？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年12月27日(周二) 晚上7:40 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 为什么不兼容到andriod7？ … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月27日(周二) 晚上7:32 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 我有一个问题，就是你编译的这些文件是否可以在任意andriod终端模拟器中运行。 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年12月27日(周二) 晚上7:18 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Lzhiyong/android-sdk-tools] 无法正常打包 (Issue #26) 使用我在android-sdk里面提供的cmake试试，官方的cmake是不支持在安卓端使用ndk的，android-sdk/cmake/bin/cmake # 修改build.py，大概80行左右，把cmake改为你的路径，注意要改为你的android-sdk/cmake/bin/cmake command = ["/data/user/0/com.termux/files/home/android-sdk/cmake/bin/cmake", "-GNinja" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 可执行文件都是ndk编译的，与使用哪个终端无关，与编译时使用的plaform有关，我都是使用api 28进行编译的，也就是说android 9以下可能缺失某些函数，文件或许不能正常执行，找不到某些符号 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 其实还是为了减少打补丁，这也就是为什么android-sdk-tools要使用 api 30来进行编译，你看termux官方的android-tools的补丁是非常多的，每次更新都要重新打补丁，还是挺麻烦的 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个我也不知道，NDK没有提供相关的函数，可以判断一个可执行文件或者动态库所支持的libc版本

其实编译不通过也没什么关系，可以等到以后有条件了再进行编译，我提供这些工具目的是，可以方便在设备上随时随地 编译 调试 自己的app

最终目标还是利用这些工具构建自己的app
