### ISSUE TITLE
Can't build on Fedora 37

### ISSUE THREAD

**Issue by JavkhlanK** [lzhiyong/android-sdk-tools#28]
I'm trying to build aapt2 locally. Could you please try to find out what's wrong for me?

I first cloned this repo using `git clone`, then ran `python3 get_source.py --tags platform-tools-33.0.3`. That took a while but failed shortly before the end with something like "unknown tag", so I `cd`'d into a submodule and ran `git tag`. That didn't show `platform-tools-33.0.31`, so I manually checked out the submodule revisions mentioned online on GitHub in all submodules. After that, running `git status` in the android-sdk-tools folder showed "nothing to commit, working tree clean". I used git 2.39.1 btw.

Anyway, after that I ran `python3 build.py --ndk=/var/lib/android/linux/SDK/ndk/25.1.8937393/ --abi=arm64-v8a --build=build/arm64-v8a --protoc=/home/jkhon/Downloads/protoc-21.12/bin/protoc` and that failed. This got printed out in red:  
```
CMake Error at src/abseil-cpp/CMake/Googletest/DownloadGTest.cmake:23 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  src/abseil-cpp/CMakeLists.txt:158 (include)
```

and here's CMake's log files:  
[CMakeOutput.log](https://github.com/Lzhiyong/android-sdk-tools/files/10530922/CMakeOutput.log)  
[CMakeError.log](https://github.com/Lzhiyong/android-sdk-tools/files/10530923/CMakeError.log)

Any idea what could be wrong? CMake apparently is at version 3.25.2 for me.

**Comment by Lzhiyong** [comment]
I don't know where the problem is, please download `release/android-sdk-tools-source.zip` to compile and try to see if it can be built successfully

```bash
python build.py \
    --ndk=/path/to/android-ndk-xxx \
    --abi=arm64-v8a \
    --build=build/aarch64 \
    --target=aapt2
```

**Comment by JavkhlanK** [comment]
I did that and now build is failing at expat with an error message similar to fwupd/fwupd#93. I'll try to build it on a Debian 11 image.

**Comment by JavkhlanK** [comment]
If anyone else experiences a similar image, just try building on a Debian or Ubuntu image.
