### ISSUE TITLE
C and CXX compiler identification is unknown

### ISSUE THREAD

**Issue by magbicaleman** [lzhiyong/android-sdk-tools#30]
When running
`python build.py  --ndk=android_sdk/ndk/23.1.7779620  --abi=arm64-v8a`

I'm getting the following error
```
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:18 (project):
  The CMAKE_C_COMPILER:

    android_sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
  
  CMake Error at CMakeLists.txt:18 (project):
  The CMAKE_CXX_COMPILER:

    android_sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
 ```
 
 In the ` android_sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/` there is no `linux-x86` just `linux-x86_64`
 
 I ran  `export CC=android_sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang` and one for `CXX` but resulted in the same error.

**Comment by magbicaleman** [comment]
I also tried using the `android-sdk-tools-static-aarch64.zip` and replacing the `platform-tools` and `build-tools` in their respective folder and still got the same error I've been trying to resolve, which is:
```
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:mergeReleaseResources'.
[RUN_GRADLEW] > Multiple task action failures occurred:
[RUN_GRADLEW]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
[RUN_GRADLEW]       > AAPT2 aapt2-7.4.1-8841542-linux Daemon #0: Daemon startup failed
[RUN_GRADLEW]         This should not happen under normal circumstances, please file an issue if it does.
```

**Comment by lzhiyong** [comment]
> I also tried using the `android-sdk-tools-static-aarch64.zip` and replacing the `platform-tools` and `build-tools` in their respective folder and still got the same error I've been trying to resolve, which is:
> 
> ```
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Execution failed for task ':app:mergeReleaseResources'.
> [RUN_GRADLEW] > Multiple task action failures occurred:
> [RUN_GRADLEW]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
> [RUN_GRADLEW]       > AAPT2 aapt2-7.4.1-8841542-linux Daemon #0: Daemon startup failed
> [RUN_GRADLEW]         This should not happen under normal circumstances, please file an issue if it does.
> ```

replace the aapt2-*-linux.jar with your aapt2

`find ~/.gradle -name 'aapt2-*-linux.jar' -type f | xargs -I{} jar -u -f {} -C /path/to/your_dir aapt2`

note:
`/path/to/your_dir aapt2` not `/path/to/your_dir/aapt2`

**Comment by lzhiyong** [comment]
> When running `python build.py --ndk=android_sdk/ndk/23.1.7779620 --abi=arm64-v8a`
> 
> I'm getting the following error
>

try to specify the full path of ndk
`python build.py --ndk=/path/to/android_sdk/ndk/23.1.7779620 --abi=arm64-v8a`

**Comment by magbicaleman** [comment]
> > When running `python build.py --ndk=android_sdk/ndk/23.1.7779620 --abi=arm64-v8a`
> > I'm getting the following error
> 
> try to specify the full path of ndk `python build.py --ndk=/path/to/android_sdk/ndk/23.1.7779620 --abi=arm64-v8a`

My apologies, I was given it the full path, I just omitted it from the issue.

**Comment by magbicaleman** [comment]
I'm trying to run this command in a linux aarch64, got the following error. I was using the `skdmanager` install of the `ndk` instead of a downloaded version from here:
- https://github.com/android/ndk/wiki/Unsupported-Downloads

After making that adjustment I got the following error

```
python build.py --ndk=/path/to/omitted/s/android-ndk-r23c --abi=arm64-v8a
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /path/to/omitted/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /path/to/omitted/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/path/to/omitted/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /path/to/omitted/android-sdk-tools-source/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/ninja cmTC_2020c && [1/2] Building C object CMakeFiles/cmTC_2020c.dir/testCCompiler.c.o
    FAILED: CMakeFiles/cmTC_2020c.dir/testCCompiler.c.o 
    /path/to/omitted/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -o CMakeFiles/cmTC_2020c.dir/testCCompiler.c.o -c /path/to/omitted/android-sdk-tools-source/build/CMakeFiles/CMakeTmp/testCCompiler.c
    qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
    ninja: build stopped: subcommand failed.
    
  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:18 (project)
  ```

**Comment by lzhiyong** [comment]
try to build with [termux-ndk](https://github.com/lzhiyong/termux-ndk) on native Termux, don't use proot or qemu
