### ISSUE TITLE
34.0.0

### ISSUE THREAD

**Issue by victorwads** [lzhiyong/android-sdk-tools#32]
hey, first of all. thanks you for supporting arm arch6.. i´ve developing using android studio on my android phone and tablet thanks to your work. for a couple of mounths.

i want to know if you're planning to update for de 34.0.0 version for arm too.

**Comment by lzhiyong** [comment]
[https://github.com/lzhiyong/android-sdk-tools/releases/tag/34.0.3](https://github.com/lzhiyong/android-sdk-tools/releases/tag/34.0.3)

**Comment by victorwads** [comment]
Thank You so Much @lzhiyong.

I really appreciate it!!! I'm programming using Android Studio on my Cellphone and my Android Tablet.
And since i found this repo i was able to build every project that i tried!

**Comment by victorwads** [comment]
@lzhiyong the only thing i couldn't get to work on Android studio is the Layout Previews cause they also use native libraries.

If u know something about it, or how to compile this, i would appreciate so much too.
