### ISSUE TITLE
could you please add apksigner in build-tools?

### ISSUE THREAD

**Issue by likfe** [lzhiyong/android-sdk-tools#33]
The [apksigner](https://developer.android.com/tools/apksigner) tool, available in revision 24.0.3 and higher of the Android SDK Build Tools, lets you sign APKs and confirm that an APK's signature will be verified successfully on all versions of the Android platform supported by that APK.

In Android project build work flow, **zipalign and apksigner is necessary.**

could you please add apksigner in build-tools?

**Comment by lzhiyong** [comment]
apksigner and d8 are in the android-sdk/build-tools, they are both jar files

**Comment by likfe** [comment]
It turns out that I used it wrongly. My problem. Sorry.
