### ISSUE TITLE
aapt2 35.0.2 shared library issue

### ISSUE THREAD

**Issue by uweseimet** [lzhiyong/android-sdk-tools#40]
The fact that aapt2 35.0.2 is not linked statically but dynamically causes an issue, at least on some platforms:

>uname -a
Linux ora1 6.5.0-1027-oracle #27~22.04.1-Ubuntu SMP Sat Jul 20 13:14:31 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
>ldd aapt2
./aapt2: error while loading shared libraries: /lib/aarch64-linux-gnu/libc.so: invalid ELF header

With the statically linked aapt2 from previous releases everything was fine.

I would like to suggest to also link the 35.0.2 tools statically, in order to ensure portability.

**Comment by lzhiyong** [comment]
the next version will provide a statically linked version

**Comment by uweseimet** [comment]
@lzhiyong Any plans when you are going to release the next version? I am asking because I would like to build apps for the Android 15 API, and as far as I can tell this requires a current version of aapt2.

**Comment by lzhiyong** [comment]
Please wait for upstream updates. the current version released by Google is 35.0.2

**Comment by uweseimet** [comment]
Well, the problem is that I canmot use your binaries of the current version. Is there any chance that you rebuild them and link them statically?

**Comment by lzhiyong** [comment]
The statically linked version has been uploaded

**Comment by uweseimet** [comment]
@lzhiyong Great, thank you! I will drop you a note later whether about whether everything works as it should.

**Comment by uweseimet** [comment]
@lzhiyong Just want to confirm that the new libraries work fine and I could successfully update my projects to API 35.
