### ISSUE TITLE
Can't execute arm64 binaries (version 35.0.2)

### ISSUE THREAD

**Issue by allofee** [lzhiyong/android-sdk-tools#44]
I downloaded the v35 version ([android-sdk-tools-aarch64.zip](https://github.com/lzhiyong/android-sdk-tools/releases/download/35.0.2/android-sdk-tools-aarch64.zip)) to my arm64 server (Ubuntu 20.04) but couldn't execute any binary.

Bash keeps complaining "No such file found." I tried adding the "execute" permission to the file and updating the owner and group, but neither worked.

Then I downloaded the v34 version and it worked.

No idea what happened.

**Comment by lzhiyong** [comment]
34.0.3 is statically linked,  35.0.2 is not

**Comment by uweseimet** [comment]
This appears to be the same issue as I reported in https://github.com/lzhiyong/android-sdk-tools/issues/40.

@lzhiyong Do you plan to build a statically linked release of 35.0.2? Google have already released library bugfixes that can only be used with building against the latest API. I need to use some of these libraries soon, but the this is not possible with the current release.
It would be a pity if I had to build on x86 again, but I need to update my apps, and with the current release binaries this is impossible.

**Comment by lzhiyong** [comment]
The statically linked version has been uploaded
